### ISSUE TITLE
Widget does not render ok when inside a tab

### ISSUE THREAD

**Issue by michaelgerritsen** [ivosturm/GoogleMapsCustomMarker#10]
Hi Ivo,

We use the Google Maps custom marker in our project. We work with tabs a lot and the widget doesn't seems render ok when it is within a tab. Furthermore I miss the option to set the overall zoom level. Could you please look into this? I attached a screenshot how it shows up inside a tab in our project.
If you have any questions feel free to contact me!

![image](https://user-images.githubusercontent.com/37400167/37583905-bcea2f02-2b53-11e8-8687-f7f6773a08a2.png)

Regards,

Michael

**Comment by ivosturm** [comment]
Hi Michael,

What is the exact scenario of your page with tab containers and my widget? I have seen it working well, so probably a scenario I did not test. If you let me know the exact page layout, so I can reproduce, I will pick this up next week.

**Comment by michaelgerritsen** [comment]
Hi Ivo,

Thanks for your response. I decided to make a test project for you. 
I add the package as an attachment. Just rename it to .mpk and you are good to go!

Hope to hear from you soon,

Michael 

[GoogleMapsMarkerTabs.zip](https://github.com/ivosturm/GoogleMapsCustomMarker/files/1857112/GoogleMapsMarkerTabs.zip)

**Comment by ivosturm** [comment]
Hi Michael,

I looked into it. I found the problem and it is actually not really related to the widget itself, but more to how a tab container is working.. It is a generic problem, just google ‘googlemaps inside tab pane’ and you will find similar issues.

A workaround is to make the tab pane with the Google Map the active tab pane when loading the page. The problem occurs when the tab pane is not shown yet.

A fix would be to add a check whether it is being loaded into a non-active tab pane and if so, add an event listener to the tab container: when showing the tab pane refresh the map. I, however, do not particularly like to make this check there. It would mean that it will check for all cases in which this widget is used and it will create a dependency on the tab container widget itself… Your scenario is not the most common one.

So, are you okay with putting it in the active tab pane? Else I can give you some code to solve it for your particular tab container scenario. Let me know! For now I will add this scenario in the ‘known bugs’ section.

Regards,
Ivo

Van: michaelgerritsen <notifications@github.com>
Verzonden: woensdag 28 maart 2018 20:09
Aan: ivosturm/GoogleMapsCustomMarker <GoogleMapsCustomMarker@noreply.github.com>
CC: Ivo Sturm <ivo.sturm@firstconsulting.nl>; Comment <comment@noreply.github.com>
Onderwerp: Re: [ivosturm/GoogleMapsCustomMarker] Widget does not render ok when inside a tab (#10)


Hi Ivo,

Thanks for your response. I decided to make a test project for you.
I add the package as an attachment. Just rename it to .mpk and you are good to go!

Hope to hear from you soon,

Michael

GoogleMapsMarkerTabs.zip<https://github.com/ivosturm/GoogleMapsCustomMarker/files/1857112/GoogleMapsMarkerTabs.zip>

**Comment by ivosturm** [comment]
Also, for the zoom level; if 0, or 1 marker is shown, the single item zoom level setting will be used. For multiple markers the zoomlevel will be decided by Google with the fitBounds function, based on the position of the 2+ markers. Do I understand that you want to override that zoomlevel? What is the scenario?
