### ISSUE TITLE
Make InfoWindowLabel optional

### ISSUE THREAD

**Issue by kesslera** [ivosturm/GoogleMapsCustomMarker#18]
Hi Ivo it's me again :),

Currently the InfoWindowLabel is set with a default value and even if one sets the parameter in the Widget-Config to empty or ' ' there is still the ':' left in front of the marker label text.

For now I will fork the repository and remove the label, as it is not needed in my application.
But for future applications it would be awesome, if the label is optional. 

Best regards,
Alex

**Comment by ivosturm** [comment]
Should be fixed with version 3.2.0 of widget
