### ISSUE TITLE
Enum images do not render

### ISSUE THREAD

**Issue by RTimeSeries** [ivosturm/GoogleMapsCustomMarker#20]
When using the 'Enum based marker image' it does not render based on the Enum value. It defaults back to either the pin or default image. 

Modeler: 7.22.0

Any help will be appreciated, Thanks.

**Comment by ivosturm** [comment]
Hi,

I checked this today in Mendix 7.22.2 and it is working fine. See below a printscreen of a map with markers rendered as pins and as enum images;
![image](https://user-images.githubusercontent.com/14050522/51071539-c3d29d00-1652-11e9-81f4-a56821356725.png)

Could you let me know in what scenario you don't see them working? My modeler config for the Enum based marker images (so right side) is:
![image](https://user-images.githubusercontent.com/14050522/51071542-f2e90e80-1652-11e9-9e78-3cfeff0f62ac.png)

**Comment by RTimeSeries** [comment]
Ivo,

I just upgraded the project to 7.22.2 and that fixed it for me. Thanks so much for looking in to it.

**Comment by RTimeSeries** [comment]
Ivo,

I just upgraded the project to 7.22.2 and that fixed it for me. Thanks so much for looking in to it.
