### ISSUE TITLE
Issue with disableInfoWindowDragend

### ISSUE THREAD

**Issue by David-Sanders** [ivosturm/GoogleMapsCustomMarker#3]
I'm receiving an error saying 'disableInfoWindowDragend is not defined' when I use this widget (bothy the version for Mx6 and Mx7).  I think the problem is in line 61 of GoogleMapsCustomMarker.xml where '**disbaleInfowWindowDragend**' needs to be changed to 'disableInfoWindowDragend' (extra w and mis-spelled disable).
Also in line 574 on GoogleMapsCustomMarker.js 'if (**disableInfoWindowDragend** === false){' should be changed to 'if (**this.disableInfoWindowDragend** === false){'
These changes solved the error I was getting in the console

**Comment by ivosturm** [comment]
Thanks for sharing your fix. I will update the code and release in the AppStore later this week.

**Comment by ivosturm** [comment]
Fixed this in version 1.1.1 now published in the Mendix AppStore
