### ISSUE TITLE
Cannot determine address at this location

### ISSUE THREAD

**Issue by David-Sanders** [ivosturm/GoogleMapsCustomMarker#4]
The widget has stopped working for me... If I drag a marker to a new position I get the following: 
**Cannot determine address at this location**.
Drag the marker to update the formatted address field!

The latitude and longitude are updated correctly, but the address field is not populated.  This worked OK for a few hours and then I started receiving this message.  I tried registering for a Google Maps API key and entered this in the widget, but that doesn't seem to help.  Any suggestions?

**Comment by ivosturm** [comment]
When geocoding in high volumes (address to lat/lon or otherway around) Google will block you if you do not have a paid account. I assume you did not create a paid account. It does only occur when geocoding A LOT in a day, see: https://developers.google.com/maps/documentation/geocoding/usage-limits

Did you surpass these limits perhaps? Did you get an error/warning in the browser console?

**Comment by David-Sanders** [comment]
Hi Ivo

 

I do not think it is the volume of requests – I only have 7 markers on my form and a single one when I drill-down to be able to drag a marker.  Also, it fails at the start of a new day too.  I do not get any warning or error in the browser – it just seems it is not returning a formatted address in this part (line 564 on)

this.geocoder.geocode({

                                                latLng: position

                                  }, lang.hitch(this,function(responses) {

 

On line 572 I changed the dragend message to

marker.formatted_address = 'Cannot determine address at this location. '+ position; and I get this:



 

The configuration of the widget is



Is there any way to investigate what’s going on?  I tried turning on the logging option but didn’t see which node to watch

 

Regards… Dave

**Comment by ivosturm** [comment]
Hi David,

I can't see the attachment (not sure why), so am not seeing the widget settings. If needed you can email the settings to: ivo.sturm@firstconsulting.nl.

I fixed your issue nr 3 and deployed that version to a sandbox app. I also added the status code from the geocoder call, which should be OK in case of results. In case status != OK, the status will be shown in the pop-up. Can you try this new version 1.2.0 from the AppStore and see what status you are getting from Google?

Also, if you want to check a live running version, I deployed the demo app to a sandbox:

https://googlemapscustomma.mxapps.io

**Comment by David-Sanders** [comment]
Hi Ivo

 

Using the latest version I could see that the issue I had was DENIED. I had a play around with the settings and it turned out the issue was with the port of the runtime – I was running on 8079 which was denied. I changed it to 8080 and it all works as expected. You live and learn…

 

Thanks for your help

 

Regards… Dave

 

David Sanders

Solution Architect

e-ServiceSuite 

 

tel +44 1494 468980

mobile +44 7710 377761

email david.sanders@westoverconsulting.co.uk

 

web   http://www.e-servicesuite.co.uk <http://www.e-servicesuite.co.uk/>
