### ISSUE TITLE
Refreshing context dataview fetches wrong data

### ISSUE THREAD

**Issue by Mcpoowl** [ivosturm/GoogleMapsCustomMarker#7]
Hi Ivo,

Back again! :-)

Ran into the issue that, when I refresh my context object is refreshed, the widget fetches the wrong data.

Info:
The widget is in a dataview (EventMap)
![image](https://user-images.githubusercontent.com/2244753/32275041-05f80428-bf0a-11e7-88be-58d5022c74e6.png)

The locations are in a seperate entity (AssetContainer) (with a constraint)
![image](https://user-images.githubusercontent.com/2244753/32275069-17532fa4-bf0a-11e7-818b-138384b3778b.png)

Initially the data loads fine as is seen by the logging of the widget (159 markers are retrieved, of the correct entity)
![image](https://user-images.githubusercontent.com/2244753/32275100-31cc8ff6-bf0a-11e7-9e0a-cbdeb51e02a9.png)

When issueing a refresh (Refresh EventMap) the widget centers on a marker at 0.0 / 0.0, and I see in the console that there's one retrieve done, which is the contextObject, and not the LocationObjects

![image](https://user-images.githubusercontent.com/2244753/32275110-3df5182a-bf0a-11e7-8abe-89100e8d01cc.png)

I tested with the 'normal' Google Maps widget, and that one does work correctly.

**Comment by ivosturm** [comment]
Fixed with release 2.0.1 of the widget
