### ISSUE TITLE
Enhancement: On click microflow button styling

### ISSUE THREAD

**Issue by Mcpoowl** [ivosturm/GoogleMapsCustomMarker#8]
Hi Ivo,

Back again ;-)
When I select an on click microflow in the widget, there's automatically a buton created in the infowindow, which is great, and was exactly what I was looking for. However, the styling of the info window is a bit off when the button is shown:

![image](https://user-images.githubusercontent.com/2244753/34821887-557046d0-f6c5-11e7-8b85-12b5ac01d9a7.png)

Besides that, I think it would be a great addition if we could:

1) Set the label of the created button
2) set some classes the button should have, to make the buttons more in line with the rest of the application.

Would like to hear what you think!

PS: Congrats on being chosen as an MVP! ;-)
Regards,
Paul

**Comment by ivosturm** [comment]
Hi fellow MVP 😊,

About the styling, you probably mean the overflow which is creating a scrollbar? About the additions:


  1.  Will add the setting of the label for the button as a setting;
  2.  Do you mean add some default Mendix classes like btn-default etc? Or do you mean the ability to add some class yourself on which some customer specific styling is applied?

Let me know!



Van: Paul Ketelaars [mailto:notifications@github.com]
Verzonden: donderdag 11 januari 2018 11:48
Aan: ivosturm/GoogleMapsCustomMarker <GoogleMapsCustomMarker@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Onderwerp: [ivosturm/GoogleMapsCustomMarker] Enhancement: On click microflow button styling (#8)


Hi Ivo,

Back again ;-)
When I select an on click microflow in the widget, there's automatically a buton created in the infowindow, which is great, and was exactly what I was looking for. However, the styling of the info window is a bit off when the button is shown:

[image]<https://user-images.githubusercontent.com/2244753/34821887-557046d0-f6c5-11e7-8b85-12b5ac01d9a7.png>

Besides that, I think it would be a great addition if we could:

  1.  Set the label of the created button
  2.  set some classes the button should have, to make the buttons more in line with the rest of the application.

Would like to hear what you think!

Regards,
Paul

**Comment by Mcpoowl** [comment]
I was indeed talking about the overflow. A width and height property for the tooltip would suffice I'd say

The default buttons would be a great start, however, being able to enter your custom classes (as you can on the default Mendix elements) would be even better.

**Comment by ivosturm** [comment]
I just uploaded a new version (2.3.0) to the AppStore with two extra settings in the ‘Interaction’ tab to cater for your two requests!

Van: Paul Ketelaars [mailto:notifications@github.com]
Verzonden: donderdag 11 januari 2018 12:34
Aan: ivosturm/GoogleMapsCustomMarker <GoogleMapsCustomMarker@noreply.github.com>
CC: Ivo Sturm <ivo.sturm@firstconsulting.nl>; Comment <comment@noreply.github.com>
Onderwerp: Re: [ivosturm/GoogleMapsCustomMarker] Enhancement: On click microflow button styling (#8)


I was indeed talking about the overflow. A width and height property for the tooltip would suffice I'd say

The default buttons would be a great start, however, being able to enter your custom classes (as you can on the default Mendix elements) would be even better.

**Comment by ivosturm** [comment]
I just uploaded a new version (2.3.0) to the AppStore with two extra settings in the ‘Interaction’ tab to cater for your two requests!


Van: Paul Ketelaars [mailto:notifications@github.com]
Verzonden: donderdag 11 januari 2018 12:34
Aan: ivosturm/GoogleMapsCustomMarker <GoogleMapsCustomMarker@noreply.github.com>
CC: Ivo Sturm <ivo.sturm@firstconsulting.nl>; Comment <comment@noreply.github.com>
Onderwerp: Re: [ivosturm/GoogleMapsCustomMarker] Enhancement: On click microflow button styling (#8)


I was indeed talking about the overflow. A width and height property for the tooltip would suffice I'd say

The default buttons would be a great start, however, being able to enter your custom classes (as you can on the default Mendix elements) would be even better.

**Comment by Mcpoowl** [comment]
Works like a charm @ivosturm. Thanks again!
